/* This file is automatically generated by Lemon from input grammar
** source file "parse.y".
*/
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 19 "parse.y"

    #include "AST.h"

    using namespace iedb;
#line 35 "parse.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef TK_SPACE
#define TK_SPACE                           1
#define TK_STRING                          2
#define TK_HEX                             3
#define TK_NUMBER_INT                      4
#define TK_NUMBER_FLOAT                    5
#define TK_NAME                            6
#define TK_COMMA                           7
#define TK_SEMI                            8
#define TK_DOT                             9
#define TK_PARENTHESIS_LEFT               10
#define TK_PARENTHESIS_RIGHT              11
#define TK_BRACKET_LEFT                   12
#define TK_BRACKET_RIGHT                  13
#define TK_BRACE_LEFT                     14
#define TK_BRACE_RIGHT                    15
#define TK_PLUS                           16
#define TK_MINUS                          17
#define TK_STAR                           18
#define TK_SLASH                          19
#define TK_MORE_EQUAL                     20
#define TK_LESS_EQUAL                     21
#define TK_NOT_EQUAL                      22
#define TK_MORE                           23
#define TK_LESS                           24
#define TK_BANG                           25
#define TK_EQUAL                          26
#define TK_BIT_OR                         27
#define TK_BIT_AND                        28
#define TK_PERCENT                        29
#define TK_NOT                            30
#define TK_AND                            31
#define TK_OR                             32
#define TK_SELECT                         33
#define TK_CREATE                         34
#define TK_UPDATE                         35
#define TK_INSERT                         36
#define TK_DELETE                         37
#define TK_DROP                           38
#define TK_FROM                           39
#define TK_WHERE                          40
#define TK_ORDER                          41
#define TK_GROUP                          42
#define TK_BY                             43
#define TK_TABLE                          44
#define TK_INT                            45
#define TK_FLOAT                          46
#define TK_TEXT                           47
#define TK_INTO                           48
#define TK_VALUES                         49
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    ParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is ParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    ParseARG_SDECL     A static variable declaration for the %extra_argument
**    ParseARG_PDECL     A parameter declaration for the %extra_argument
**    ParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    ParseARG_STORE     Code to store %extra_argument into yypParser
**    ParseARG_FETCH     Code to extract %extra_argument from yypParser
**    ParseCTX_*         As ParseARG_ except for %extra_context
**    YYREALLOC          Name of the realloc() function to use
**    YYFREE             Name of the free() function to use
**    YYDYNSTACK         True if stack space should be extended on heap
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
**    YY_MIN_DSTRCTR     Minimum symbol value that has a destructor
**    YY_MAX_DSTRCTR     Maximum symbol value that has a destructor
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 71
#define YYACTIONTYPE unsigned char
#define ParseTOKENTYPE  token* 
typedef union {
  int yyinit;
  ParseTOKENTYPE yy0;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define ParseARG_SDECL AST*ast ;
#define ParseARG_PDECL ,AST*ast 
#define ParseARG_PARAM ,ast 
#define ParseARG_FETCH AST*ast =yypParser->ast ;
#define ParseARG_STORE yypParser->ast =ast ;
#define YYREALLOC realloc
#define YYFREE free
#define YYDYNSTACK 0
#define ParseCTX_SDECL
#define ParseCTX_PDECL
#define ParseCTX_PARAM
#define ParseCTX_FETCH
#define ParseCTX_STORE
#define YYNSTATE             63
#define YYNRULE              54
#define YYNRULE_WITH_ACTION  54
#define YYNTOKEN             50
#define YY_MAX_SHIFT         62
#define YY_MIN_SHIFTREDUCE   95
#define YY_MAX_SHIFTREDUCE   148
#define YY_ERROR_ACTION      149
#define YY_ACCEPT_ACTION     150
#define YY_NO_ACTION         151
#define YY_MIN_REDUCE        152
#define YY_MAX_REDUCE        205
#define YY_MIN_DSTRCTR       0
#define YY_MAX_DSTRCTR       0
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif

/* Macro to determine if stack space has the ability to grow using
** heap memory.
*/
#if YYSTACKDEPTH<=0 || YYDYNSTACK
# define YYGROWABLESTACK 1
#else
# define YYGROWABLESTACK 0
#endif

/* Guarantee a minimum number of initial stack slots.
*/
#if YYSTACKDEPTH<=0
# undef YYSTACKDEPTH
# define YYSTACKDEPTH 2  /* Need a minimum stack size */
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (154)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */    62,  188,   28,  192,   49,   53,  188,   21,   18,  187,
 /*    10 */    54,   14,   20,   18,  187,   50,   53,  188,  112,  113,
 /*    20 */   150,   54,   14,   20,   18,  187,   51,   53,  188,  114,
 /*    30 */    27,  199,   54,   14,   20,   18,  187,   57,   53,  188,
 /*    40 */   110,  111,  188,   54,   14,   20,   18,  187,   29,  188,
 /*    50 */   186,  188,   17,   54,   14,   20,   18,  187,   19,  187,
 /*    60 */   191,   56,  188,  132,    9,  200,   54,   14,   20,   18,
 /*    70 */   187,  107,  108,  109,  106,  188,   11,   10,    5,   55,
 /*    80 */    14,   20,   18,  187,    7,    2,  102,  119,  120,  118,
 /*    90 */   115,  116,   35,  117,  198,    1,   42,   23,   48,   37,
 /*   100 */    33,   39,  107,  108,  109,  106,  188,   58,   60,    5,
 /*   110 */    52,   15,   20,   18,  187,  136,  138,  137,  139,  144,
 /*   120 */   145,  146,   16,   24,   25,  205,   44,   30,   31,   32,
 /*   130 */   204,   34,   22,   36,  197,   38,   41,   40,   13,  190,
 /*   140 */    43,   46,   45,   12,   47,    6,    3,    4,    7,    8,
 /*   150 */   152,   59,   26,   61,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    51,   57,   66,   67,   55,   56,   57,   63,   64,   65,
 /*    10 */    61,   62,   63,   64,   65,   55,   56,   57,   18,   19,
 /*    20 */    50,   61,   62,   63,   64,   65,   55,   56,   57,   29,
 /*    30 */    68,   69,   61,   62,   63,   64,   65,   55,   56,   57,
 /*    40 */    16,   17,   57,   61,   62,   63,   64,   65,   56,   57,
 /*    50 */    65,   57,    6,   61,   62,   63,   64,   65,   64,   65,
 /*    60 */    67,   56,   57,   11,   60,   70,   61,   62,   63,   64,
 /*    70 */    65,    3,    4,    5,    6,   57,   59,   58,   10,   61,
 /*    80 */    62,   63,   64,   65,   32,   40,   18,   20,   21,   22,
 /*    90 */    23,   24,   52,   26,   69,   33,   34,    7,   36,   37,
 /*   100 */    38,   11,    3,    4,    5,    6,   57,   42,   54,   10,
 /*   110 */    41,   62,   63,   64,   65,    2,    3,    4,    5,   45,
 /*   120 */    46,   47,    7,   53,   52,    0,   11,    8,    6,   44,
 /*   130 */     0,    8,    6,   39,    0,    8,   44,    6,   10,    0,
 /*   140 */     8,    6,   49,   10,   48,    7,   43,   43,   32,   31,
 /*   150 */     0,    8,    6,   39,   71,   71,   71,   71,   71,   71,
 /*   160 */    71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
 /*   170 */    71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
 /*   180 */    71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
 /*   190 */    71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
 /*   200 */    71,   71,   71,   71,
};
#define YY_SHIFT_COUNT    (62)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (150)
static const unsigned char yy_shift_ofst[] = {
 /*     0 */    62,   68,   99,   99,   99,   99,   99,   99,   99,   99,
 /*    10 */    99,   99,  113,   46,   67,   67,  113,   74,    0,    0,
 /*    20 */    24,   24,   45,   46,   65,   69,   45,   90,  115,   52,
 /*    30 */   125,  119,  122,   85,  130,  123,  126,   94,  134,  127,
 /*    40 */   128,  131,   92,  139,  132,  133,   93,  135,   96,  138,
 /*    50 */   138,  138,  103,  116,  118,  118,  116,  138,  104,  150,
 /*    60 */   143,  146,  114,
};
#define YY_REDUCE_COUNT (26)
#define YY_REDUCE_MIN   (-64)
#define YY_REDUCE_MAX   (72)
static const signed char yy_reduce_ofst[] = {
 /*     0 */   -30,  -51,  -40,  -29,  -18,   -8,    5,   18,   49,  -56,
 /*    10 */    -6,  -15,  -64,  -38,    4,    4,   -7,   -5,   17,   17,
 /*    20 */    19,   19,   40,   25,   54,   70,   72,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
 /*    10 */   149,  149,  149,  149,  181,  180,  149,  149,  185,  184,
 /*    20 */   183,  182,  153,  149,  157,  155,  153,  149,  149,  149,
 /*    30 */   149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
 /*    40 */   149,  149,  149,  149,  149,  149,  149,  149,  149,  160,
 /*    50 */   154,  156,  149,  162,  179,  178,  161,  158,  149,  149,
 /*    60 */   149,  149,  149,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  ParseARG_SDECL                /* A place to hold %extra_argument */
  ParseCTX_SDECL                /* A place to hold %extra_context */
  yyStackEntry *yystackEnd;           /* Last entry in the stack */
  yyStackEntry *yystack;              /* The parser stack */
  yyStackEntry yystk0[YYSTACKDEPTH];  /* Initial stack space */
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void ParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "SPACE",
  /*    2 */ "STRING",
  /*    3 */ "HEX",
  /*    4 */ "NUMBER_INT",
  /*    5 */ "NUMBER_FLOAT",
  /*    6 */ "NAME",
  /*    7 */ "COMMA",
  /*    8 */ "SEMI",
  /*    9 */ "DOT",
  /*   10 */ "PARENTHESIS_LEFT",
  /*   11 */ "PARENTHESIS_RIGHT",
  /*   12 */ "BRACKET_LEFT",
  /*   13 */ "BRACKET_RIGHT",
  /*   14 */ "BRACE_LEFT",
  /*   15 */ "BRACE_RIGHT",
  /*   16 */ "PLUS",
  /*   17 */ "MINUS",
  /*   18 */ "STAR",
  /*   19 */ "SLASH",
  /*   20 */ "MORE_EQUAL",
  /*   21 */ "LESS_EQUAL",
  /*   22 */ "NOT_EQUAL",
  /*   23 */ "MORE",
  /*   24 */ "LESS",
  /*   25 */ "BANG",
  /*   26 */ "EQUAL",
  /*   27 */ "BIT_OR",
  /*   28 */ "BIT_AND",
  /*   29 */ "PERCENT",
  /*   30 */ "NOT",
  /*   31 */ "AND",
  /*   32 */ "OR",
  /*   33 */ "SELECT",
  /*   34 */ "CREATE",
  /*   35 */ "UPDATE",
  /*   36 */ "INSERT",
  /*   37 */ "DELETE",
  /*   38 */ "DROP",
  /*   39 */ "FROM",
  /*   40 */ "WHERE",
  /*   41 */ "ORDER",
  /*   42 */ "GROUP",
  /*   43 */ "BY",
  /*   44 */ "TABLE",
  /*   45 */ "INT",
  /*   46 */ "FLOAT",
  /*   47 */ "TEXT",
  /*   48 */ "INTO",
  /*   49 */ "VALUES",
  /*   50 */ "cmd",
  /*   51 */ "colnames",
  /*   52 */ "where_statement",
  /*   53 */ "order_statement",
  /*   54 */ "group_statement",
  /*   55 */ "exprs",
  /*   56 */ "or_expr",
  /*   57 */ "item",
  /*   58 */ "op1",
  /*   59 */ "op2",
  /*   60 */ "op3",
  /*   61 */ "and_expr",
  /*   62 */ "compare_expr",
  /*   63 */ "compute_expr1",
  /*   64 */ "compute_expr2",
  /*   65 */ "factor",
  /*   66 */ "data_values",
  /*   67 */ "value",
  /*   68 */ "colsdef",
  /*   69 */ "coldef",
  /*   70 */ "type",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "cmd ::= SELECT colnames FROM NAME where_statement order_statement group_statement SEMI",
 /*   1 */ "where_statement ::=",
 /*   2 */ "where_statement ::= WHERE exprs",
 /*   3 */ "order_statement ::=",
 /*   4 */ "order_statement ::= ORDER BY exprs",
 /*   5 */ "group_statement ::=",
 /*   6 */ "group_statement ::= GROUP BY exprs",
 /*   7 */ "colnames ::= STAR",
 /*   8 */ "colnames ::= exprs",
 /*   9 */ "exprs ::= exprs COMMA or_expr",
 /*  10 */ "exprs ::= or_expr",
 /*  11 */ "item ::= NAME",
 /*  12 */ "item ::= HEX",
 /*  13 */ "item ::= NUMBER_INT",
 /*  14 */ "item ::= NUMBER_FLOAT",
 /*  15 */ "op1 ::= PLUS",
 /*  16 */ "op1 ::= MINUS",
 /*  17 */ "op2 ::= STAR",
 /*  18 */ "op2 ::= SLASH",
 /*  19 */ "op2 ::= PERCENT",
 /*  20 */ "op3 ::= MORE",
 /*  21 */ "op3 ::= LESS",
 /*  22 */ "op3 ::= EQUAL",
 /*  23 */ "op3 ::= NOT_EQUAL",
 /*  24 */ "op3 ::= MORE_EQUAL",
 /*  25 */ "op3 ::= LESS_EQUAL",
 /*  26 */ "or_expr ::= or_expr OR and_expr",
 /*  27 */ "or_expr ::= and_expr",
 /*  28 */ "and_expr ::= and_expr AND compare_expr",
 /*  29 */ "and_expr ::= compare_expr",
 /*  30 */ "compare_expr ::= compare_expr op3 compute_expr1",
 /*  31 */ "compare_expr ::= compute_expr1",
 /*  32 */ "compute_expr1 ::= compute_expr1 op1 compute_expr2",
 /*  33 */ "compute_expr1 ::= compute_expr2",
 /*  34 */ "compute_expr2 ::= compute_expr2 op2 factor",
 /*  35 */ "compute_expr2 ::= factor",
 /*  36 */ "factor ::= item",
 /*  37 */ "factor ::= PARENTHESIS_LEFT or_expr PARENTHESIS_RIGHT",
 /*  38 */ "cmd ::= INSERT INTO NAME VALUES PARENTHESIS_LEFT data_values PARENTHESIS_RIGHT SEMI",
 /*  39 */ "data_values ::= data_values COMMA value",
 /*  40 */ "data_values ::= value",
 /*  41 */ "value ::= STRING",
 /*  42 */ "value ::= NUMBER_INT",
 /*  43 */ "value ::= HEX",
 /*  44 */ "value ::= NUMBER_FLOAT",
 /*  45 */ "cmd ::= CREATE TABLE NAME PARENTHESIS_LEFT colsdef PARENTHESIS_RIGHT SEMI",
 /*  46 */ "colsdef ::= colsdef COMMA coldef",
 /*  47 */ "colsdef ::= coldef",
 /*  48 */ "coldef ::= NAME type",
 /*  49 */ "type ::= INT",
 /*  50 */ "type ::= FLOAT",
 /*  51 */ "type ::= TEXT",
 /*  52 */ "cmd ::= DELETE FROM NAME where_statement SEMI",
 /*  53 */ "cmd ::= DROP TABLE NAME SEMI",
};
#endif /* NDEBUG */


#if YYGROWABLESTACK
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int oldSize = 1 + (int)(p->yystackEnd - p->yystack);
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = oldSize*2 + 100;
  idx = (int)(p->yytos - p->yystack);
  if( p->yystack==p->yystk0 ){
    pNew = YYREALLOC(0, newSize*sizeof(pNew[0]));
    if( pNew==0 ) return 1;
    memcpy(pNew, p->yystack, oldSize*sizeof(pNew[0]));
  }else{
    pNew = YYREALLOC(p->yystack, newSize*sizeof(pNew[0]));
    if( pNew==0 ) return 1;
  }
  p->yystack = pNew;
  p->yytos = &p->yystack[idx];
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
            yyTracePrompt, oldSize, newSize);
  }
#endif
  p->yystackEnd = &p->yystack[newSize-1];
  return 0;
}
#endif /* YYGROWABLESTACK */

#if !YYGROWABLESTACK
/* For builds that do no have a growable stack, yyGrowStack always
** returns an error.
*/
# define yyGrowStack(X) 1
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to ParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void ParseInit(void *yypRawParser ParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  ParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
  yypParser->yystack = yypParser->yystk0;
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to Parse and ParseFree.
*/
void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) ParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    ParseCTX_STORE
    ParseInit(yypParser ParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* Parse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  ParseARG_FETCH
  ParseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void ParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;

  /* In-lined version of calling yy_pop_parser_stack() for each
  ** element left in the stack */
  yyStackEntry *yytos = pParser->yytos;
  while( yytos>pParser->yystack ){
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sPopping %s\n",
        yyTracePrompt,
        yyTokenName[yytos->major]);
    }
#endif
    if( yytos->major>=YY_MIN_DSTRCTR ){
      yy_destructor(pParser, yytos->major, &yytos->minor);
    }
    yytos--;
  }

#if YYGROWABLESTACK
  if( pParser->yystack!=pParser->yystk0 ) YYFREE(pParser->yystack);
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void ParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  ParseFinalize(p);
  (*freeProc)(p);
}
#endif /* Parse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int ParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int ParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   ParseARG_FETCH
   ParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   ParseARG_STORE /* Suppress warning about unused %extra_argument var */
   ParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  ParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
  yytos = yypParser->yytos;
  if( yytos>yypParser->yystackEnd ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
    yytos = yypParser->yytos;
    assert( yytos <= yypParser->yystackEnd );
  }
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    50,  /* (0) cmd ::= SELECT colnames FROM NAME where_statement order_statement group_statement SEMI */
    52,  /* (1) where_statement ::= */
    52,  /* (2) where_statement ::= WHERE exprs */
    53,  /* (3) order_statement ::= */
    53,  /* (4) order_statement ::= ORDER BY exprs */
    54,  /* (5) group_statement ::= */
    54,  /* (6) group_statement ::= GROUP BY exprs */
    51,  /* (7) colnames ::= STAR */
    51,  /* (8) colnames ::= exprs */
    55,  /* (9) exprs ::= exprs COMMA or_expr */
    55,  /* (10) exprs ::= or_expr */
    57,  /* (11) item ::= NAME */
    57,  /* (12) item ::= HEX */
    57,  /* (13) item ::= NUMBER_INT */
    57,  /* (14) item ::= NUMBER_FLOAT */
    58,  /* (15) op1 ::= PLUS */
    58,  /* (16) op1 ::= MINUS */
    59,  /* (17) op2 ::= STAR */
    59,  /* (18) op2 ::= SLASH */
    59,  /* (19) op2 ::= PERCENT */
    60,  /* (20) op3 ::= MORE */
    60,  /* (21) op3 ::= LESS */
    60,  /* (22) op3 ::= EQUAL */
    60,  /* (23) op3 ::= NOT_EQUAL */
    60,  /* (24) op3 ::= MORE_EQUAL */
    60,  /* (25) op3 ::= LESS_EQUAL */
    56,  /* (26) or_expr ::= or_expr OR and_expr */
    56,  /* (27) or_expr ::= and_expr */
    61,  /* (28) and_expr ::= and_expr AND compare_expr */
    61,  /* (29) and_expr ::= compare_expr */
    62,  /* (30) compare_expr ::= compare_expr op3 compute_expr1 */
    62,  /* (31) compare_expr ::= compute_expr1 */
    63,  /* (32) compute_expr1 ::= compute_expr1 op1 compute_expr2 */
    63,  /* (33) compute_expr1 ::= compute_expr2 */
    64,  /* (34) compute_expr2 ::= compute_expr2 op2 factor */
    64,  /* (35) compute_expr2 ::= factor */
    65,  /* (36) factor ::= item */
    65,  /* (37) factor ::= PARENTHESIS_LEFT or_expr PARENTHESIS_RIGHT */
    50,  /* (38) cmd ::= INSERT INTO NAME VALUES PARENTHESIS_LEFT data_values PARENTHESIS_RIGHT SEMI */
    66,  /* (39) data_values ::= data_values COMMA value */
    66,  /* (40) data_values ::= value */
    67,  /* (41) value ::= STRING */
    67,  /* (42) value ::= NUMBER_INT */
    67,  /* (43) value ::= HEX */
    67,  /* (44) value ::= NUMBER_FLOAT */
    50,  /* (45) cmd ::= CREATE TABLE NAME PARENTHESIS_LEFT colsdef PARENTHESIS_RIGHT SEMI */
    68,  /* (46) colsdef ::= colsdef COMMA coldef */
    68,  /* (47) colsdef ::= coldef */
    69,  /* (48) coldef ::= NAME type */
    70,  /* (49) type ::= INT */
    70,  /* (50) type ::= FLOAT */
    70,  /* (51) type ::= TEXT */
    50,  /* (52) cmd ::= DELETE FROM NAME where_statement SEMI */
    50,  /* (53) cmd ::= DROP TABLE NAME SEMI */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -8,  /* (0) cmd ::= SELECT colnames FROM NAME where_statement order_statement group_statement SEMI */
    0,  /* (1) where_statement ::= */
   -2,  /* (2) where_statement ::= WHERE exprs */
    0,  /* (3) order_statement ::= */
   -3,  /* (4) order_statement ::= ORDER BY exprs */
    0,  /* (5) group_statement ::= */
   -3,  /* (6) group_statement ::= GROUP BY exprs */
   -1,  /* (7) colnames ::= STAR */
   -1,  /* (8) colnames ::= exprs */
   -3,  /* (9) exprs ::= exprs COMMA or_expr */
   -1,  /* (10) exprs ::= or_expr */
   -1,  /* (11) item ::= NAME */
   -1,  /* (12) item ::= HEX */
   -1,  /* (13) item ::= NUMBER_INT */
   -1,  /* (14) item ::= NUMBER_FLOAT */
   -1,  /* (15) op1 ::= PLUS */
   -1,  /* (16) op1 ::= MINUS */
   -1,  /* (17) op2 ::= STAR */
   -1,  /* (18) op2 ::= SLASH */
   -1,  /* (19) op2 ::= PERCENT */
   -1,  /* (20) op3 ::= MORE */
   -1,  /* (21) op3 ::= LESS */
   -1,  /* (22) op3 ::= EQUAL */
   -1,  /* (23) op3 ::= NOT_EQUAL */
   -1,  /* (24) op3 ::= MORE_EQUAL */
   -1,  /* (25) op3 ::= LESS_EQUAL */
   -3,  /* (26) or_expr ::= or_expr OR and_expr */
   -1,  /* (27) or_expr ::= and_expr */
   -3,  /* (28) and_expr ::= and_expr AND compare_expr */
   -1,  /* (29) and_expr ::= compare_expr */
   -3,  /* (30) compare_expr ::= compare_expr op3 compute_expr1 */
   -1,  /* (31) compare_expr ::= compute_expr1 */
   -3,  /* (32) compute_expr1 ::= compute_expr1 op1 compute_expr2 */
   -1,  /* (33) compute_expr1 ::= compute_expr2 */
   -3,  /* (34) compute_expr2 ::= compute_expr2 op2 factor */
   -1,  /* (35) compute_expr2 ::= factor */
   -1,  /* (36) factor ::= item */
   -3,  /* (37) factor ::= PARENTHESIS_LEFT or_expr PARENTHESIS_RIGHT */
   -8,  /* (38) cmd ::= INSERT INTO NAME VALUES PARENTHESIS_LEFT data_values PARENTHESIS_RIGHT SEMI */
   -3,  /* (39) data_values ::= data_values COMMA value */
   -1,  /* (40) data_values ::= value */
   -1,  /* (41) value ::= STRING */
   -1,  /* (42) value ::= NUMBER_INT */
   -1,  /* (43) value ::= HEX */
   -1,  /* (44) value ::= NUMBER_FLOAT */
   -7,  /* (45) cmd ::= CREATE TABLE NAME PARENTHESIS_LEFT colsdef PARENTHESIS_RIGHT SEMI */
   -3,  /* (46) colsdef ::= colsdef COMMA coldef */
   -1,  /* (47) colsdef ::= coldef */
   -2,  /* (48) coldef ::= NAME type */
   -1,  /* (49) type ::= INT */
   -1,  /* (50) type ::= FLOAT */
   -1,  /* (51) type ::= TEXT */
   -5,  /* (52) cmd ::= DELETE FROM NAME where_statement SEMI */
   -4,  /* (53) cmd ::= DROP TABLE NAME SEMI */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  ParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  ParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  ParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* cmd ::= SELECT colnames FROM NAME where_statement order_statement group_statement SEMI */
#line 25 "parse.y"
{
    ast->type = token_type::select;
    ast->target_table = yymsp[-4].minor.yy0;

    ast->master = yymsp[-6].minor.yy0;
    ast->where = yymsp[-3].minor.yy0;
    ast->order = yymsp[-2].minor.yy0;
    ast->group = yymsp[-1].minor.yy0;
    }
#line 1160 "parse.c"
        break;
      case 1: /* where_statement ::= */
#line 34 "parse.y"
{yymsp[1].minor.yy0=nullptr; }
#line 1165 "parse.c"
        break;
      case 2: /* where_statement ::= WHERE exprs */
#line 35 "parse.y"
{yymsp[-1].minor.yy0=yymsp[0].minor.yy0;}
#line 1170 "parse.c"
        break;
      case 3: /* order_statement ::= */
      case 5: /* group_statement ::= */ yytestcase(yyruleno==5);
#line 36 "parse.y"
{yymsp[1].minor.yy0=nullptr;}
#line 1176 "parse.c"
        break;
      case 4: /* order_statement ::= ORDER BY exprs */
      case 6: /* group_statement ::= GROUP BY exprs */ yytestcase(yyruleno==6);
#line 37 "parse.y"
{yymsp[-2].minor.yy0=yymsp[0].minor.yy0;}
#line 1182 "parse.c"
        break;
      case 7: /* colnames ::= STAR */
      case 8: /* colnames ::= exprs */ yytestcase(yyruleno==8);
      case 10: /* exprs ::= or_expr */ yytestcase(yyruleno==10);
      case 11: /* item ::= NAME */ yytestcase(yyruleno==11);
      case 12: /* item ::= HEX */ yytestcase(yyruleno==12);
      case 13: /* item ::= NUMBER_INT */ yytestcase(yyruleno==13);
      case 14: /* item ::= NUMBER_FLOAT */ yytestcase(yyruleno==14);
      case 15: /* op1 ::= PLUS */ yytestcase(yyruleno==15);
      case 16: /* op1 ::= MINUS */ yytestcase(yyruleno==16);
      case 17: /* op2 ::= STAR */ yytestcase(yyruleno==17);
      case 18: /* op2 ::= SLASH */ yytestcase(yyruleno==18);
      case 19: /* op2 ::= PERCENT */ yytestcase(yyruleno==19);
      case 20: /* op3 ::= MORE */ yytestcase(yyruleno==20);
      case 21: /* op3 ::= LESS */ yytestcase(yyruleno==21);
      case 22: /* op3 ::= EQUAL */ yytestcase(yyruleno==22);
      case 23: /* op3 ::= NOT_EQUAL */ yytestcase(yyruleno==23);
      case 24: /* op3 ::= MORE_EQUAL */ yytestcase(yyruleno==24);
      case 25: /* op3 ::= LESS_EQUAL */ yytestcase(yyruleno==25);
      case 27: /* or_expr ::= and_expr */ yytestcase(yyruleno==27);
      case 29: /* and_expr ::= compare_expr */ yytestcase(yyruleno==29);
      case 31: /* compare_expr ::= compute_expr1 */ yytestcase(yyruleno==31);
      case 33: /* compute_expr1 ::= compute_expr2 */ yytestcase(yyruleno==33);
      case 35: /* compute_expr2 ::= factor */ yytestcase(yyruleno==35);
      case 36: /* factor ::= item */ yytestcase(yyruleno==36);
      case 40: /* data_values ::= value */ yytestcase(yyruleno==40);
      case 41: /* value ::= STRING */ yytestcase(yyruleno==41);
      case 42: /* value ::= NUMBER_INT */ yytestcase(yyruleno==42);
      case 43: /* value ::= HEX */ yytestcase(yyruleno==43);
      case 44: /* value ::= NUMBER_FLOAT */ yytestcase(yyruleno==44);
      case 47: /* colsdef ::= coldef */ yytestcase(yyruleno==47);
      case 49: /* type ::= INT */ yytestcase(yyruleno==49);
      case 50: /* type ::= FLOAT */ yytestcase(yyruleno==50);
      case 51: /* type ::= TEXT */ yytestcase(yyruleno==51);
#line 41 "parse.y"
{yylhsminor.yy0=yymsp[0].minor.yy0;}
#line 1219 "parse.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 9: /* exprs ::= exprs COMMA or_expr */
      case 39: /* data_values ::= data_values COMMA value */ yytestcase(yyruleno==39);
      case 46: /* colsdef ::= colsdef COMMA coldef */ yytestcase(yyruleno==46);
#line 43 "parse.y"
{
    token* temp = yymsp[-2].minor.yy0;
    while(temp->next!= nullptr) temp = temp->next;
    temp->next = yymsp[0].minor.yy0;
    yylhsminor.yy0=yymsp[-2].minor.yy0;}
#line 1231 "parse.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 26: /* or_expr ::= or_expr OR and_expr */
      case 28: /* and_expr ::= and_expr AND compare_expr */ yytestcase(yyruleno==28);
      case 30: /* compare_expr ::= compare_expr op3 compute_expr1 */ yytestcase(yyruleno==30);
      case 32: /* compute_expr1 ::= compute_expr1 op1 compute_expr2 */ yytestcase(yyruleno==32);
      case 34: /* compute_expr2 ::= compute_expr2 op2 factor */ yytestcase(yyruleno==34);
#line 69 "parse.y"
{yymsp[-1].minor.yy0->left = yymsp[-2].minor.yy0; yymsp[-1].minor.yy0->right = yymsp[0].minor.yy0;yylhsminor.yy0=yymsp[-1].minor.yy0;}
#line 1241 "parse.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 37: /* factor ::= PARENTHESIS_LEFT or_expr PARENTHESIS_RIGHT */
#line 85 "parse.y"
{yymsp[-2].minor.yy0=yymsp[-1].minor.yy0;}
#line 1247 "parse.c"
        break;
      case 38: /* cmd ::= INSERT INTO NAME VALUES PARENTHESIS_LEFT data_values PARENTHESIS_RIGHT SEMI */
#line 91 "parse.y"
{
    ast->type = token_type::insert;
    ast->target_table = yymsp[-5].minor.yy0;
    ast->master = yymsp[-2].minor.yy0;
}
#line 1256 "parse.c"
        break;
      case 45: /* cmd ::= CREATE TABLE NAME PARENTHESIS_LEFT colsdef PARENTHESIS_RIGHT SEMI */
#line 109 "parse.y"
{
    ast->type = token_type::create;
    ast->target_table = yymsp[-4].minor.yy0;
    ast->master = yymsp[-2].minor.yy0;
}
#line 1265 "parse.c"
        break;
      case 48: /* coldef ::= NAME type */
#line 120 "parse.y"
{yymsp[-1].minor.yy0->left = yymsp[0].minor.yy0; yylhsminor.yy0=yymsp[-1].minor.yy0;}
#line 1270 "parse.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 52: /* cmd ::= DELETE FROM NAME where_statement SEMI */
#line 127 "parse.y"
{
    ast->type = token_type::Delete;
    ast->target_table = yymsp[-2].minor.yy0;
    ast->where = yymsp[-1].minor.yy0;
}
#line 1280 "parse.c"
        break;
      case 53: /* cmd ::= DROP TABLE NAME SEMI */
#line 133 "parse.y"
{
    ast->type = token_type::drop;
    ast->target_table = yymsp[-1].minor.yy0;
}
#line 1288 "parse.c"
        break;
      default:
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 11 "parse.y"

     fprintf(stdout,"Parser failed\n");
     ast->type = token_type::error;
#line 1336 "parse.c"
/************ End %parse_failure code *****************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  ParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 15 "parse.y"

    fprintf(stdout,"syntax error happened\n");
    ast->type = token_type::error;
#line 1359 "parse.c"
/************ End %syntax_error code ******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "ParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void Parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  ParseTOKENTYPE yyminor       /* The value for the token */
  ParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  ParseCTX_FETCH
  ParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
        if( yypParser->yytos>=yypParser->yystackEnd ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor ParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int ParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
