%token_prefix TK_
%token SPACE STRING HEX NUMBER NAME COMMA SEMI DOT PARENTHESIS_LEFT PARENTHESIS_RIGHT
BRACKET_LEFT BRACKET_RIGHT BRACE_LEFT BRACE_RIGHT PLUS MINUS STAR SLASH MORE LESS
BANG EQUAL BIT_OR BIT_AND NOT AND OR SELECT CREATE UPDATE
DELETE FROM WHERE ORDER GROUP BY

%include{
    #include <Token.h>


}


