/* Generated by re2c 3.1 on Mon Jan  6 16:39:21 2025 */
#line 1 "lexer.re"
#include "token.h"
namespace iedb {
#define re2c_token_process(x) { type = x; \
len = static_cast<uint32>(YYCURSOR - start); \
return type;}
    static token_type lexer_token(const char * start,const char *end,int& len){
         const char * YYCURSOR = start;
         const char * YYMARKER = YYCURSOR;
         const char * YYLIMIT = end;
         token_type type = token_type::error;

         
#line 16 "../src/lexer.cpp"
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\r':
		case ' ': goto yy2;
		case '!': goto yy4;
		case '&': goto yy6;
		case '\'': goto yy7;
		case '(': goto yy8;
		case ')': goto yy9;
		case '*': goto yy10;
		case '+': goto yy11;
		case ',': goto yy12;
		case '-': goto yy13;
		case '.': goto yy14;
		case '/': goto yy15;
		case '0': goto yy16;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy18;
		case ';': goto yy20;
		case '<': goto yy21;
		case '=': goto yy23;
		case '>': goto yy24;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'e':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'p':
		case 'q':
		case 'r':
		case 'v':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		case '[': goto yy29;
		case ']': goto yy30;
		case 'a': goto yy31;
		case 'b': goto yy32;
		case 'c': goto yy33;
		case 'd': goto yy34;
		case 'f': goto yy35;
		case 'g': goto yy36;
		case 'i': goto yy37;
		case 'n': goto yy38;
		case 'o': goto yy39;
		case 's': goto yy40;
		case 't': goto yy41;
		case 'u': goto yy42;
		case 'w': goto yy43;
		case '{': goto yy44;
		case '|': goto yy45;
		case '}': goto yy46;
		default: goto yy1;
	}
yy1:
	++YYCURSOR;
#line 59 "lexer.re"
	{printf("something wrong start at %s\n",start);type = token_type::error;len = 1;return type;}
#line 114 "../src/lexer.cpp"
yy2:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\r':
		case ' ': goto yy2;
		default: goto yy3;
	}
yy3:
#line 53 "lexer.re"
	{type = token_type::space; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 127 "../src/lexer.cpp"
yy4:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy47;
		default: goto yy5;
	}
yy5:
#line 34 "lexer.re"
	{type = token_type::bang; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 137 "../src/lexer.cpp"
yy6:
	++YYCURSOR;
#line 37 "lexer.re"
	{type = token_type::bit_and; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 142 "../src/lexer.cpp"
yy7:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\'': goto yy48;
		default: goto yy7;
	}
yy8:
	++YYCURSOR;
#line 19 "lexer.re"
	{type = token_type::parenthesis_left; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 153 "../src/lexer.cpp"
yy9:
	++YYCURSOR;
#line 20 "lexer.re"
	{type = token_type::parenthesis_right; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 158 "../src/lexer.cpp"
yy10:
	++YYCURSOR;
#line 27 "lexer.re"
	{type = token_type::star; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 163 "../src/lexer.cpp"
yy11:
	++YYCURSOR;
#line 25 "lexer.re"
	{type = token_type::plus; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 168 "../src/lexer.cpp"
yy12:
	++YYCURSOR;
#line 16 "lexer.re"
	{type = token_type::comma; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 173 "../src/lexer.cpp"
yy13:
	++YYCURSOR;
#line 26 "lexer.re"
	{type = token_type::minus; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 178 "../src/lexer.cpp"
yy14:
	++YYCURSOR;
#line 18 "lexer.re"
	{type = token_type::dot; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 183 "../src/lexer.cpp"
yy15:
	++YYCURSOR;
#line 28 "lexer.re"
	{type = token_type::slash; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 188 "../src/lexer.cpp"
yy16:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'X':
		case 'x': goto yy51;
		default: goto yy19;
	}
yy17:
#line 55 "lexer.re"
	{type = token_type::number_int; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 199 "../src/lexer.cpp"
yy18:
	yych = *(YYMARKER = ++YYCURSOR);
yy19:
	switch (yych) {
		case '.': goto yy49;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy18;
		default: goto yy17;
	}
yy20:
	++YYCURSOR;
#line 17 "lexer.re"
	{type = token_type::semi; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 221 "../src/lexer.cpp"
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy52;
		default: goto yy22;
	}
yy22:
#line 31 "lexer.re"
	{type = token_type::less; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 231 "../src/lexer.cpp"
yy23:
	++YYCURSOR;
#line 35 "lexer.re"
	{type = token_type::equal; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 236 "../src/lexer.cpp"
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy53;
		default: goto yy25;
	}
yy25:
#line 30 "lexer.re"
	{type = token_type::more; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 246 "../src/lexer.cpp"
yy26:
	yych = *++YYCURSOR;
yy27:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy28;
	}
yy28:
#line 57 "lexer.re"
	{type = token_type::name; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 319 "../src/lexer.cpp"
yy29:
	++YYCURSOR;
#line 21 "lexer.re"
	{type = token_type::bracket_left; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 324 "../src/lexer.cpp"
yy30:
	++YYCURSOR;
#line 22 "lexer.re"
	{type = token_type::bracket_right; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 329 "../src/lexer.cpp"
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy54;
		default: goto yy27;
	}
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'y': goto yy55;
		default: goto yy27;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy57;
		default: goto yy27;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy58;
		default: goto yy27;
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy59;
		case 'r': goto yy60;
		default: goto yy27;
	}
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy61;
		default: goto yy27;
	}
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy62;
		default: goto yy27;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy63;
		default: goto yy27;
	}
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy64;
		default: goto yy27;
	}
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy66;
		default: goto yy27;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy67;
		default: goto yy27;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'p': goto yy68;
		default: goto yy27;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'h': goto yy69;
		default: goto yy27;
	}
yy44:
	++YYCURSOR;
#line 23 "lexer.re"
	{type = token_type::brace_left; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 413 "../src/lexer.cpp"
yy45:
	++YYCURSOR;
#line 36 "lexer.re"
	{type = token_type::bit_or; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 418 "../src/lexer.cpp"
yy46:
	++YYCURSOR;
#line 24 "lexer.re"
	{type = token_type::brace_right; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 423 "../src/lexer.cpp"
yy47:
	++YYCURSOR;
#line 33 "lexer.re"
	{type = token_type::not_equal; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 428 "../src/lexer.cpp"
yy48:
	++YYCURSOR;
#line 56 "lexer.re"
	{type = token_type::string; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 433 "../src/lexer.cpp"
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy70;
		default: goto yy50;
	}
yy50:
	YYCURSOR = YYMARKER;
	goto yy17;
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy72;
		default: goto yy50;
	}
yy52:
	++YYCURSOR;
#line 32 "lexer.re"
	{type = token_type::less_equal; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 483 "../src/lexer.cpp"
yy53:
	++YYCURSOR;
#line 29 "lexer.re"
	{type = token_type::more_equal; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 488 "../src/lexer.cpp"
yy54:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy74;
		default: goto yy27;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy56;
	}
yy56:
#line 49 "lexer.re"
	{type = token_type::by; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 566 "../src/lexer.cpp"
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy76;
		default: goto yy27;
	}
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy77;
		default: goto yy27;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy78;
		default: goto yy27;
	}
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy79;
		default: goto yy27;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy80;
		default: goto yy27;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy81;
		default: goto yy27;
	}
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy83;
		default: goto yy27;
	}
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		case 'd': goto yy85;
		default: goto yy65;
	}
yy65:
#line 40 "lexer.re"
	{type = token_type::Or; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 680 "../src/lexer.cpp"
yy66:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy86;
		default: goto yy27;
	}
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'x': goto yy87;
		default: goto yy27;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy88;
		default: goto yy27;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy89;
		default: goto yy27;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy70;
		default: goto yy71;
	}
yy71:
#line 54 "lexer.re"
	{type = token_type::number_float; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 723 "../src/lexer.cpp"
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy72;
		default: goto yy73;
	}
yy73:
#line 58 "lexer.re"
	{type = token_type::hex; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 754 "../src/lexer.cpp"
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy75;
	}
yy75:
#line 39 "lexer.re"
	{type = token_type::And; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 826 "../src/lexer.cpp"
yy76:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy90;
		default: goto yy27;
	}
yy77:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy91;
		default: goto yy27;
	}
yy78:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy92;
		default: goto yy27;
	}
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'm': goto yy93;
		default: goto yy27;
	}
yy80:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy95;
		default: goto yy27;
	}
yy81:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy82;
	}
yy82:
#line 50 "lexer.re"
	{re2c_token_process(token_type::Int)}
#line 928 "../src/lexer.cpp"
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy84;
	}
yy84:
#line 38 "lexer.re"
	{type = token_type::Not; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 1000 "../src/lexer.cpp"
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy96;
		default: goto yy27;
	}
yy86:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy97;
		default: goto yy27;
	}
yy87:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy98;
		default: goto yy27;
	}
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy100;
		default: goto yy27;
	}
yy89:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy101;
		default: goto yy27;
	}
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy102;
		default: goto yy27;
	}
yy91:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy103;
		default: goto yy27;
	}
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy104;
		default: goto yy27;
	}
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy94;
	}
yy94:
#line 45 "lexer.re"
	{type = token_type::from; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 1120 "../src/lexer.cpp"
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'p': goto yy106;
		default: goto yy27;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy108;
		default: goto yy27;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy110;
		default: goto yy27;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy99;
	}
yy99:
#line 52 "lexer.re"
	{re2c_token_process(token_type::text)}
#line 1210 "../src/lexer.cpp"
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy111;
		default: goto yy27;
	}
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy112;
		default: goto yy27;
	}
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy114;
		default: goto yy27;
	}
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy116;
		default: goto yy27;
	}
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy105;
	}
yy105:
#line 51 "lexer.re"
	{re2c_token_process(token_type::Float)}
#line 1306 "../src/lexer.cpp"
yy106:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy107;
	}
yy107:
#line 48 "lexer.re"
	{type = token_type::group; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 1378 "../src/lexer.cpp"
yy108:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy109;
	}
yy109:
#line 47 "lexer.re"
	{type = token_type::order; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 1450 "../src/lexer.cpp"
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy118;
		default: goto yy27;
	}
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy120;
		default: goto yy27;
	}
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy113;
	}
yy113:
#line 46 "lexer.re"
	{type = token_type::where; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 1534 "../src/lexer.cpp"
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy115;
	}
yy115:
#line 42 "lexer.re"
	{type = token_type::create; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 1606 "../src/lexer.cpp"
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy117;
	}
yy117:
#line 44 "lexer.re"
	{type = token_type::Delete; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 1678 "../src/lexer.cpp"
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy119;
	}
yy119:
#line 41 "lexer.re"
	{type = token_type::select; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 1750 "../src/lexer.cpp"
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy26;
		default: goto yy121;
	}
yy121:
#line 43 "lexer.re"
	{type = token_type::update; len = static_cast<uint32>(YYCURSOR - start);return type;}
#line 1822 "../src/lexer.cpp"
}
#line 61 "lexer.re"

    }
	std::unique_ptr<std::vector<token>> token::lexer(const char *sql) {
		std::vector<token> tokens;
		auto sql_string = std::make_shared<std::string>(sql);
		auto len = strlen(sql);
		auto start = sql;
		auto end = start + len;
		while (start < end) {
			int token_len;
			//将字符串结束符号\0同样算作缓冲区中
			auto type = lexer_token(start, end + 1,  token_len);
			if (type == token_type::error)
				return nullptr;
			if(type != token_type::space)
			    tokens.emplace_back(type, static_cast<uint32>(start - sql), token_len,sql);
			start += token_len;
		}
		return std::make_unique<std::vector<token>>(tokens);
	}

	void token::print() const {
		printf("type:%d offset:%d len:%d %s\n", (int)type, offset, len,std::string(sql,offset,len).c_str());
	}

};